stages:
  - test
  - build
  - deploy

variables:
  GIT_SSL_NO_VERIFY: "1"
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Xmx1536m -DaltDeploymentRepository=nexus::default::https://nexus.beta.innovation.insee.eu/repository/maven-snapshots/ -Dmaven.repo.local=/mnt/mesos/sandbox/repo -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.artifact.threads=2"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  #MAVEN_BIN: "/opt/apache-maven-3.5.3/bin/mvn"
  SONAR_URL: "https://sonar.beta.innovation.insee.eu/"

sonarqube:
  stage: test
  only:
    - dv
  image: git-registry.stable.innovation.insee.eu/innovation/images-ci/jdk:8
  script:
    - mvn $MAVEN_CLI_OPTS verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN

tests:
  stage: test
  only:
    - branches
  except:
    - dv
  image: git-registry.stable.innovation.insee.eu/innovation/images-ci/jdk:8
  script:
    - mvn $MAVEN_CLI_OPTS test

package:
  stage: build
  only:
    - dv
    - qf
  image: git-registry.stable.innovation.insee.eu/innovation/images-ci/jdk:8
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - target/*.war
    expire_in: 1 day

.deploy: &deploy
  stage: deploy
  only:
    refs:
      - branches
    variables:
      - $NOM_BRANCHE == $CI_COMMIT_REF_NAME
  image: git-registry.stable.innovation.insee.eu/innovation/images-ci/jdk:8
  script:
    - curl -T target/*.war ftp://$FTP_USR_W:$FTP_PWD@$FTP_SERVER_W/depot/ROOT.war

deploy-dv:
  <<: *deploy
  variables:
    NOM_BRANCHE: dv
    FTP_USR_W: tomcatdev
    FTP_PWD: $FTP_PWD
    FTP_SERVER_W: dvrmeswnczlas01.ad.insee.intra

deploy-qf:
  <<: *deploy
  variables:
    NOM_BRANCHE: qf
    FTP_USR_W: tomcatrec
    FTP_PWD: $FTP_PWD
    FTP_SERVER_W: qfrmeswnczlas01.ad.insee.intra
