openapi: 3.0.0
servers:
  - url: 'http://qfrmeswnczlht01'
    description: 'Qf server'
  - url: 'http://localhost:8080/metadata-api'
    description: 'Local dev server'
info:
  description: API sur les métadonnées de l'Insee
  version: '0.1'
  title: API RMéS
tags:
  - name: nomenclatures
  - name: géographie
paths:
  '/codes/cj/n2/{code}':
    get:
      tags:
        - nomenclatures
      summary: Informations sur une catégorie juridique de niveau 2
      operationId: getcjn2
      parameters:
        - name: code
          in: path
          description: Identifiant de la catégorie juridique de niveau 2 (deux chiffres)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Opération réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategorieJuridiqueNiveauII'
            application/xml:
              schema:
                $ref: '#/components/schemas/CategorieJuridiqueNiveauII'
        '400':
          description: La syntaxe de la requête est incorrecte
        '401':
          description: Une authentification est nécessaire pour accéder à la ressource
        '404':
          description: Ressource non trouvée
        '406':
          description: L'en-tête HTTP 'Accept' contient une valeur non acceptée
        '500':
          description: Erreur interne du serveur
  '/codes/cj/n3/{code}':
    get:
      tags:
        - nomenclatures
      summary: Informations sur une catégorie juridique de niveau 3
      operationId: getcjn3
      parameters:
        - name: code
          in: path
          description: Identifiant de la catégorie juridique de niveau 3 (quatre chiffres)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Opération réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategorieJuridiqueNiveauIII'
            application/xml:
              schema:
                $ref: '#/components/schemas/CategorieJuridiqueNiveauIII'
        '400':
          description: La syntaxe de la requête est incorrecte
        '401':
          description: Une authentification est nécessaire pour accéder à la ressource
        '404':
          description: Ressource non trouvée
        '406':
          description: L'en-tête HTTP 'Accept' contient une valeur non acceptée
        '500':
          description: Erreur interne du serveur
  '/codes/nafr2/classe/{code}':
    get:
      tags:
        - nomenclatures
      summary: Informations sur une classe de la NAF rév.2 identifiée par son code
      operationId: getnafr2n4
      parameters:
        - name: code
          in: path
          description: 'Code de la classe (deux chiffres, un point, deux chiffres)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClasseNAF2008'
        '400':
          description: La syntaxe de la requête est incorrecte
        '401':
          description: Une authentification est nécessaire pour accéder à la ressource
        '404':
          description: Ressource non trouvée
        '406':
          description: L'en-tête HTTP 'Accept' contient une valeur non acceptée
        '500':
          description: Erreur interne du serveur
  '/codes/nafr2/sousClasse/{code}':
    get:
      tags:
        - nomenclatures
      summary: Informations sur une sous-classe de la NAF rév.2 identifiée par son code
      operationId: getnafr2n5
      parameters:
        - name: code
          in: path
          description: >-
            Code de la sous-classe (deux chiffres, un point, deux chiffres et
            une lettre majuscule)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SousClasseNAF2008'
        '400':
          description: La syntaxe de la requête est incorrecte
        '401':
          description: Une authentification est nécessaire pour accéder à la ressource
        '404':
          description: Ressource non trouvée
        '406':
          description: L'en-tête HTTP 'Accept' contient une valeur non acceptée
        '500':
          description: Erreur interne du serveur
  '/geo/commune/{code}':
    get:
      tags:
        - géographie
      summary: >-
        Informations sur une commune française identifiée par son code (cinq
        caractères)
      description: >-
        Cette requête renvoie également les communes des collectivités
        d'Outre-Mer
      operationId: getcogcom
      parameters:
        - name: code
          in: path
          description: Code de la commune (cinq caractères)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Opération réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Commune'
            application/xml:
              schema:
                $ref: '#/components/schemas/Commune'
        '400':
          description: La syntaxe de la requête est incorrecte
        '401':
          description: Une authentification est nécessaire pour accéder à la ressource
        '404':
          description: Ressource non trouvée
        '406':
          description: L'en-tête HTTP 'Accept' contient une valeur non acceptée
        '500':
          description: Erreur interne du serveur
  '/geo/region/{code}':
    get:
      tags:
        - géographie
      summary: >-
        Informations sur une région française identifiée par son code (deux
        chiffres)
      operationId: getcogreg
      parameters:
        - name: code
          in: path
          description: Code de la région (deux chiffres)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Opération réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Region'
            application/xml:
              schema:
                $ref: '#/components/schemas/Region'
        '400':
          description: La syntaxe de la requête est incorrecte
        '401':
          description: Une authentification est nécessaire pour accéder à la ressource
        '404':
          description: Ressource non trouvée
        '406':
          description: L'en-tête HTTP 'Accept' contient une valeur non acceptée
        '500':
          description: Erreur interne du serveur
  '/geo/pays/{code}':
    get:
      tags:
        - géographie
      summary: Informations sur un pays identifié par son code (cinq chiffres)
      operationId: getcogpay
      parameters:
        - name: code
          in: path
          description: 'Code du pays (cinq chiffres, débutant par 99)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Opération réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pays'
            application/xml:
              schema:
                $ref: '#/components/schemas/Pays'
        '400':
          description: La syntaxe de la requête est incorrecte
        '401':
          description: Une authentification est nécessaire pour accéder à la ressource
        '404':
          description: Ressource non trouvée
        '406':
          description: L'en-tête HTTP 'Accept' contient une valeur non acceptée
        '500':
          description: Erreur interne du serveur
components:
  schemas:
    CategorieJuridiqueNiveauII:
      type: object
      description: Objet représentant une catégorie juridique (niveau 2)
      properties:
        code:
          type: string
          example: '10'
          xml:
            attribute: true
        uri:
          type: string
          example: 'http://id.insee.fr/codes/cj/n2/10'
          xml:
            attribute: true
        intitule:
          type: string
          example: Entrepreneur individuel
          xml:
            name: Intitule
    CategorieJuridiqueNiveauIII:
      type: object
      description: Objet représentant une catégorie juridique détaillée (niveau 3)
      properties:
        code:
          type: string
          example: '7112'
          xml:
            attribute: true
        uri:
          type: string
          example: 'http://id.insee.fr/codes/cj/n3/7112'
          xml:
            attribute: true
        intitule:
          type: string
          example: Autorité administrative ou publique indépendante
          xml:
            name: Intitule
    ClasseNAF2008:
      type: object
      description: Objet représentant une classe de la NAF 2008 (rév. 2)
      properties:
        code:
          type: string
          example: '27.40'
          xml:
            attribute: true
        uri:
          type: string
          example: 'http://id.insee.fr/codes/nafr2/sousClasse/27.40'
          xml:
            attribute: true
        intitule:
          type: string
          example: Fabrication d'appareils d'éclairage électrique
          xml:
            name: Intitule
    SousClasseNAF2008:
      type: object
      description: Objet représentant une sous-classe de la NAF 2008 (rév. 2)
      properties:
        code:
          type: string
          example: 27.40Z
          xml:
            attribute: true
        uri:
          type: string
          example: 'http://id.insee.fr/codes/nafr2/sousClasse/27.40Z'
          xml:
            attribute: true
        intitule:
          type: string
          example: Fabrication d'appareils d'éclairage électrique
          xml:
            name: Intitule
    Region:
      type: object
      description: Objet représentant une région
      properties:
        code:
          type: string
          example: '27'
          xml:
            attribute: true
        uri:
          type: string
          example: 'http://id.insee.fr/geo/region/27'
          xml:
            attribute: true
        intitule:
          type: string
          example: Bourgogne-Franche-Comté
          xml:
            name: Intitule
    Commune:
      type: object
      description: Objet représentant une commune
      properties:
        code:
          type: string
          example: '55323'
          xml:
            attribute: true
        uri:
          type: string
          example: 'http://id.insee.fr/geo/commune/55323'
          xml:
            attribute: true
        intitule:
          type: string
          example: Martincourt-sur-Meuse
          xml:
            name: Intitule
    Pays:
      type: object
      description: Objet représentant un pays
      properties:
        code:
          type: string
          example: '99217'
          xml:
            attribute: true
        uri:
          type: string
          example: 'http://id.insee.fr/geo/pays/99217'
          xml:
            attribute: true
        intitule:
          type: string
          example: Japon
          xml:
            name: Intitule
